name: Portfolio CI

on:
  push:
    branches:
      - master

jobs:
  build-portfolio:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: gen_sha
        name: Generate short SHA
        run: echo "shortSha=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dusan.work/
          push: true
          tags: "ghcr.io/${{ github.repository }}/portfolio:latest,ghcr.io/${{ github.repository }}/portfolio:${{ steps.gen_sha.outputs.shortSha }}"